import type { HeroDef } from "@/entities/types";

export const sgtBubbles: HeroDef = {
	id: "sgt_bubbles",
	name: "SGT. BUBBLES",
	faction: "ura",
	category: "infantry",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"......####......",
					".....#SssS#.....",
					".....#S..S#.....",
					"......#ss#......",
					".....#bbbb#.....",
					"..SS#bBBBBb#SS..",
					"..SS#bBBBBb#SS..",
					"..SS#bBbBBb#SS..",
					"...##bBBBBb##...",
					"....#BBBBBB#....",
					"....##cccc##....",
					".....#CCCC#.....",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
			],
			walk: [
				[
					"......####......",
					".....#SssS#.....",
					".....#S..S#.....",
					"......#ss#......",
					".....#bbbb#.....",
					"..SS#bBBBBb#SS..",
					"..SS#bBBBBb#SS..",
					"..SS#bBbBBb#SS..",
					"...##bBBBBb##...",
					"....#BBBBBB#....",
					"....##cccc##....",
					".....#CCCC#.....",
					".....#WWWW#.....",
					".....##WW##.....",
					"....##...###....",
					"................",
				],
				[
					"......####......",
					".....#SssS#.....",
					".....#S..S#.....",
					"......#ss#......",
					".....#bbbb#.....",
					"..SS#bBBBBb#SS..",
					"..SS#bBBBBb#SS..",
					"..SS#bBbBBb#SS..",
					"...##bBBBBb##...",
					"....#BBBBBB#....",
					"....##cccc##....",
					".....#CCCC#.....",
					".....#WWWW#.....",
					".....#WW##......",
					"....###..##.....",
					"................",
				],
			],
			attack: [
				[
					"......####......",
					".....#SssS#.....",
					".....#S..S#.....",
					"......#ss#......",
					".....#bbbb#.....",
					"..SS#bBBBBb#SS..",
					"..SS#bBBBBb#SS##",
					"..SS#bBbBBb#SScc",
					"...##bBBBBb##.cc",
					"....#BBBBBB#..##",
					"....##cccc##....",
					".....#CCCC#.....",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
				[
					"......####......",
					".....#SssS#.....",
					".....#S..S#.....",
					"......#ss#......",
					".....#bbbb#..##.",
					"..SS#bBBBBb#SScc",
					"..SS#bBBBBb#SS##",
					"..SS#bBbBBb#SS..",
					"...##bBBBBb##...",
					"....#BBBBBB#....",
					"....##cccc##....",
					".....#CCCC#.....",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
			],
		},
		animationRates: { walk: 6, attack: 10 },
	},

	hp: 120,
	armor: 3,
	damage: 15,
	range: 1,
	attackCooldown: 1.0,
	speed: 14,
	visionRadius: 7,

	cost: {},
	populationCost: 0,
	trainTime: 0,
	trainedAt: "command_post",

	unlockedAt: "mission_1",

	portraitId: "sgt_bubbles",
	unlockMission: "mission_1",
	unlockDescription: "Available from the start — Rambo-style warrior-leader",

	abilities: [
		{
			id: "rally_cry",
			name: "Rally Cry",
			description: "Nearby allies gain +2 damage for 10 seconds",
			cooldown: 30,
		},
	],

	tags: ["IsUnit", "IsHero", "IsCombat"],
};
