import type { CharacterGear, CharacterTraits, WeaponData } from "./types";

export const WEAPONS: Record<string, WeaponData> = {
	"service-pistol": {
		id: "service-pistol",
		name: "SERVICE PISTOL",
		type: "PISTOL",
		damage: 2,
		fireRate: 0.4,
		bulletSpeed: 60,
		recoil: 0.02,
		range: 30,
		visualType: "PISTOL_GRIP",
	},
	"fish-cannon": {
		id: "fish-cannon",
		name: "HEAVY FISH-CANNON",
		type: "MACHINE_GUN",
		damage: 1,
		fireRate: 0.1,
		bulletSpeed: 90,
		recoil: 0.05,
		range: 50,
		visualType: "FISH_CANNON",
	},
	"bubble-gun": {
		id: "bubble-gun",
		name: "BUBBLE SNIPER",
		type: "RIFLE",
		damage: 5,
		fireRate: 0.8,
		bulletSpeed: 120,
		recoil: 0.08,
		range: 80,
		visualType: "BUBBLE_GUN",
	},
	"scatter-shell": {
		id: "scatter-shell",
		name: "SCATTER SHELL",
		type: "SHOTGUN",
		damage: 8,
		fireRate: 1.2,
		bulletSpeed: 45,
		recoil: 0.15,
		range: 15,
		visualType: "SHOTGUN",
	},
	"clam-mortar": {
		id: "clam-mortar",
		name: "CLAM MORTAR",
		type: "LAUNCHER",
		damage: 25,
		fireRate: 2.5,
		bulletSpeed: 30,
		recoil: 0.2,
		range: 40,
		visualType: "MORTAR",
	},
	"silt-needle": {
		id: "silt-needle",
		name: "SILT NEEDLE",
		type: "PISTOL",
		damage: 3,
		fireRate: 0.25,
		bulletSpeed: 80,
		recoil: 0.01,
		range: 50,
		visualType: "NEEDLE_GUN",
	},
};

export const CHARACTERS: Record<string, { traits: CharacterTraits; gear: CharacterGear }> = {
	bubbles: {
		traits: {
			id: "bubbles",
			name: "SGT. BUBBLES",
			furColor: "#5D4037",
			eyeColor: "#111",
			whiskerLength: 0.3,
			grizzled: false,
			baseSpeed: 14,
			baseHealth: 100,
			climbSpeed: 10,
		},
		gear: {
			headgear: "bandana",
			vest: "tactical",
			backgear: "radio",
			weaponId: "service-pistol",
		},
	},
	whiskers: {
		traits: {
			id: "whiskers",
			name: "GEN. WHISKERS",
			furColor: "#8D6E63",
			eyeColor: "#222",
			whiskerLength: 0.8,
			grizzled: true,
			baseSpeed: 10,
			baseHealth: 200,
			climbSpeed: 6,
			unlockRequirement: "Rescue from Prison Camp (Coordinate 5, 5)",
		},
		gear: {
			headgear: "beret",
			vest: "heavy",
			backgear: "none",
			weaponId: "fish-cannon",
		},
	},
	splash: {
		traits: {
			id: "splash",
			name: "CPL. SPLASH",
			furColor: "#4E342E",
			eyeColor: "#00ccff",
			whiskerLength: 0.2,
			grizzled: false,
			baseSpeed: 18,
			baseHealth: 80,
			climbSpeed: 15,
			unlockRequirement: "Secure the Silt-shadow Crossing",
		},
		gear: {
			headgear: "helmet",
			vest: "tactical",
			backgear: "scuba",
			weaponId: "bubble-gun",
		},
	},
	fang: {
		traits: {
			id: "fang",
			name: "SGT. FANG",
			furColor: "#333",
			eyeColor: "#ff0000",
			whiskerLength: 0.4,
			grizzled: true,
			baseSpeed: 12,
			baseHealth: 150,
			climbSpeed: 8,
			unlockRequirement: "Rescue from Scale-Guard Stronghold (Coordinate 12, -5)",
		},
		gear: {
			headgear: "none",
			vest: "heavy",
			backgear: "none",
			weaponId: "fish-cannon",
		},
	},
	marina: {
		traits: {
			id: "marina",
			name: "MEDIC MARINA",
			furColor: "#6D4C41",
			eyeColor: "#66bb6a",
			whiskerLength: 0.25,
			grizzled: false,
			baseSpeed: 16,
			baseHealth: 80,
			climbSpeed: 12,
			unlockRequirement: "Rescue from Healer's Grove (Coordinate -15, 20)",
		},
		gear: {
			headgear: "helmet",
			vest: "tactical",
			backgear: "radio",
			weaponId: "silt-needle",
		},
	},
	muskrat: {
		traits: {
			id: "muskrat",
			name: "PVT. MUSKRAT",
			furColor: "#3E2723",
			eyeColor: "#8d6e63",
			whiskerLength: 0.5,
			grizzled: false,
			baseSpeed: 11,
			baseHealth: 120,
			climbSpeed: 14,
			unlockRequirement: "Rescue from Gas Depot (Coordinate 8, 8)",
		},
		gear: {
			headgear: "bandana",
			vest: "tactical",
			backgear: "scuba",
			weaponId: "scatter-shell",
		},
	},
};

export const UPGRADE_COSTS = {
	speed: 200,
	health: 200,
	damage: 300,
};

export const CHAR_PRICES: Record<string, number> = {
	bubbles: 0,
	whiskers: 1000,
	splash: 500,
	fang: 750,
	marina: 600,
	muskrat: 400,
};
