import type { UnitDef } from "@/entities/types";

export const crocChampion: UnitDef = {
	id: "croc_champion",
	name: "CROC CHAMPION",
	faction: "scale_guard",
	category: "infantry",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"....######......",
					"...#GGGGGG#.....",
					"...#GGggGG#.....",
					"...#GGGGGG#.....",
					"..##rrrrrr##....",
					".GG#rRRRRr#GG##.",
					".G.#rRRRRr#.G#c#",
					".G.#rRRRRr#.G#c#",
					"..##RRRRRR##.#c#",
					"...#RRRRRR#..#c#",
					"...#CCCCCC#..##.",
					"...#CCCCCC#.....",
					"...#WWWWWW#.....",
					"...#WWWWWW#.....",
					"..####..####....",
					"................",
				],
			],
			walk: [
				[
					"....######......",
					"...#GGGGGG#.....",
					"...#GGggGG#.....",
					"...#GGGGGG#.....",
					"..##rrrrrr##....",
					".GG#rRRRRr#GG##.",
					".G.#rRRRRr#.G#c#",
					".G.#rRRRRr#.G#c#",
					"..##RRRRRR##.#c#",
					"...#RRRRRR#..#c#",
					"...#CCCCCC#..##.",
					"...#CCCCCC#.....",
					"...#WWWWWW#.....",
					"...##WWWW##.....",
					"..##....####....",
					"................",
				],
				[
					"....######......",
					"...#GGGGGG#.....",
					"...#GGggGG#.....",
					"...#GGGGGG#.....",
					"..##rrrrrr##....",
					".GG#rRRRRr#GG##.",
					".G.#rRRRRr#.G#c#",
					".G.#rRRRRr#.G#c#",
					"..##RRRRRR##.#c#",
					"...#RRRRRR#..#c#",
					"...#CCCCCC#..##.",
					"...#CCCCCC#.....",
					"...#WWWWWW#.....",
					"...#WWWW##......",
					"..####..###.....",
					"................",
				],
			],
			attack: [
				[
					"....######......",
					"...#GGGGGG#.....",
					"...#GGggGG#.....",
					"...#GGGGGG#.....",
					"..##rrrrrr##....",
					".GG#rRRRRr#GG###",
					".G.#rRRRRr#.Gccc",
					".G.#rRRRRr#.Gccc",
					"..##RRRRRR##.###",
					"...#RRRRRR#.....",
					"...#CCCCCC#.....",
					"...#CCCCCC#.....",
					"...#WWWWWW#.....",
					"...#WWWWWW#.....",
					"..####..####....",
					"................",
				],
				[
					"....######......",
					"...#GGGGGG#.....",
					"...#GGggGG#.....",
					"...#GGGGGG#.###.",
					"..##rrrrrr##ccc.",
					".GG#rRRRRr#Gccc.",
					".G.#rRRRRr#.###.",
					".G.#rRRRRr#.G...",
					"..##RRRRRR##....",
					"...#RRRRRR#.....",
					"...#CCCCCC#.....",
					"...#CCCCCC#.....",
					"...#WWWWWW#.....",
					"...#WWWWWW#.....",
					"..####..####....",
					"................",
				],
			],
		},
		animationRates: { walk: 4, attack: 6 },
	},

	hp: 200,
	armor: 5,
	damage: 25,
	range: 1,
	attackCooldown: 2.0,
	speed: 6,
	visionRadius: 6,

	cost: { fish: 200, salvage: 100 },
	populationCost: 2,
	trainTime: 45,
	trainedAt: "spawning_pool",

	unlockedAt: "mission_9",

	aiProfile: {
		states: ["idle", "patrol", "chase", "attack", "berserk"],
		defaultState: "patrol",
		aggroRange: 8,
		specialBehavior: "berserk",
	},

	drops: [
		{ type: "salvage", min: 15, max: 25, chance: 0.8 },
		{ type: "fish", min: 10, max: 20, chance: 0.5 },
	],

	tags: ["IsUnit", "IsCombat", "IsElite"],
};
