import type { UnitDef } from "@/entities/types";

export const gator: UnitDef = {
	id: "gator",
	name: "GATOR",
	faction: "scale_guard",
	category: "infantry",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					".....######.....",
					"....#GGGGGG#....",
					"....#GGggGG#....",
					".....######.....",
					"....#rrrrrr#....",
					"..GG#rRRRRr#GG..",
					"..G.#rRRRRr#.G..",
					"..G.#rRRRRr#.G..",
					"...##RRRRRR##...",
					"....#RRRRRR#....",
					"....#CCCCCC#....",
					"....#CCCCCC#....",
					"....#WWWWWW#....",
					"....#WWWWWW#....",
					"...####..####...",
					"................",
				],
			],
			walk: [
				[
					".....######.....",
					"....#GGGGGG#....",
					"....#GGggGG#....",
					".....######.....",
					"....#rrrrrr#....",
					"..GG#rRRRRr#GG..",
					"..G.#rRRRRr#.G..",
					"..G.#rRRRRr#.G..",
					"...##RRRRRR##...",
					"....#RRRRRR#....",
					"....#CCCCCC#....",
					"....#CCCCCC#....",
					"....#WWWWWW#....",
					"....##WWWW##....",
					"...##....####...",
					"................",
				],
				[
					".....######.....",
					"....#GGGGGG#....",
					"....#GGggGG#....",
					".....######.....",
					"....#rrrrrr#....",
					"..GG#rRRRRr#GG..",
					"..G.#rRRRRr#.G..",
					"..G.#rRRRRr#.G..",
					"...##RRRRRR##...",
					"....#RRRRRR#....",
					"....#CCCCCC#....",
					"....#CCCCCC#....",
					"....#WWWWWW#....",
					"....#WWWW##.....",
					"...####..###....",
					"................",
				],
			],
			attack: [
				[
					".....######.....",
					"....#GGGGGG#....",
					"....#GGggGG#....",
					".....######.....",
					"....#rrrrrr#....",
					"..GG#rRRRRr#GG..",
					"..G.#rRRRRr#.GGG",
					"..G.#rRRRRr#.GGG",
					"...##RRRRRR##...",
					"....#RRRRRR#....",
					"....#CCCCCC#....",
					"....#CCCCCC#....",
					"....#WWWWWW#....",
					"....#WWWWWW#....",
					"...####..####...",
					"................",
				],
				[
					".....######.....",
					"....#GGGGGG#....",
					"....#GGggGG#....",
					".....######.....",
					"....#rrrrrr#....",
					"..GG#rRRRRr#GGGG",
					"..G.#rRRRRr#.GGG",
					"..G.#rRRRRr#.G..",
					"...##RRRRRR##...",
					"....#RRRRRR#....",
					"....#CCCCCC#....",
					"....#CCCCCC#....",
					"....#WWWWWW#....",
					"....#WWWWWW#....",
					"...####..####...",
					"................",
				],
			],
		},
		animationRates: { walk: 4, attack: 8 },
	},

	hp: 120,
	armor: 4,
	damage: 18,
	range: 1,
	attackCooldown: 1.8,
	speed: 5,
	visionRadius: 5,

	cost: { fish: 100, salvage: 40 },
	populationCost: 1,
	trainTime: 30,
	trainedAt: "spawning_pool",

	unlockedAt: "mission_1",

	canSubmerge: true,

	aiProfile: {
		states: ["idle", "patrol", "chase", "attack", "ambush"],
		defaultState: "patrol",
		aggroRange: 6,
		specialBehavior: "ambush",
	},

	drops: [
		{ type: "salvage", min: 5, max: 12, chance: 0.5 },
		{ type: "fish", min: 3, max: 8, chance: 0.3 },
	],

	tags: ["IsUnit", "IsCombat"],
};
