import type { UnitDef } from "@/entities/types";

export const viper: UnitDef = {
	id: "viper",
	name: "VIPER",
	faction: "scale_guard",
	category: "ranged",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"......####......",
					".....#GGGG#.....",
					".....#GggG#.....",
					"......####......",
					".....#rrrr#.....",
					"...G#rRRRRr#G...",
					"...G#rRRRRr#G..#",
					"...G#rRRRRr#G.#P",
					"....##RRRR##.#P#",
					".....#RRRR#..#P.",
					".....#GGGG#..#..",
					".....#GGGG#.....",
					".....#GGGG#.....",
					".....#gggg#.....",
					"....###..###....",
					"................",
				],
			],
			walk: [
				[
					"......####......",
					".....#GGGG#.....",
					".....#GggG#.....",
					"......####......",
					".....#rrrr#.....",
					"...G#rRRRRr#G...",
					"...G#rRRRRr#G..#",
					"...G#rRRRRr#G.#P",
					"....##RRRR##.#P#",
					".....#RRRR#..#P.",
					".....#GGGG#..#..",
					".....#GGGG#.....",
					".....#GGGG#.....",
					".....##gg##.....",
					"....##...###....",
					"................",
				],
				[
					"......####......",
					".....#GGGG#.....",
					".....#GggG#.....",
					"......####......",
					".....#rrrr#.....",
					"...G#rRRRRr#G...",
					"...G#rRRRRr#G..#",
					"...G#rRRRRr#G.#P",
					"....##RRRR##.#P#",
					".....#RRRR#..#P.",
					".....#GGGG#..#..",
					".....#GGGG#.....",
					".....#GGGG#.....",
					".....#gg##......",
					"....###..##.....",
					"................",
				],
			],
			attack: [
				[
					"......####......",
					".....#GGGG#.....",
					".....#GggG#.....",
					"......####......",
					".....#rrrr#.....",
					"...G#rRRRRr#G...",
					"...G#rRRRRr#G..#",
					"...G#rRRRRr#G.#P",
					"....##RRRR##.#PP",
					".....#RRRR#..#P.",
					".....#GGGG#..#..",
					".....#GGGG#.....",
					".....#GGGG#.....",
					".....#gggg#.....",
					"....###..###....",
					"................",
				],
				[
					"......####......",
					".....#GGGG#.....",
					".....#GggG#.....",
					"......####......",
					".....#rrrr#..#..",
					"...G#rRRRRr#G#P.",
					"...G#rRRRRr#G#PP",
					"...G#rRRRRr#G.#P",
					"....##RRRR##..#.",
					".....#RRRR#.....",
					".....#GGGG#.....",
					".....#GGGG#.....",
					".....#GGGG#.....",
					".....#gggg#.....",
					"....###..###....",
					"................",
				],
			],
		},
		animationRates: { walk: 8, attack: 10 },
	},

	hp: 35,
	armor: 0,
	damage: 8,
	range: 5,
	attackCooldown: 1.5,
	speed: 8,
	visionRadius: 7,

	cost: { fish: 60, salvage: 30 },
	populationCost: 1,
	trainTime: 22,
	trainedAt: "spawning_pool",

	unlockedAt: "mission_3",

	aiProfile: {
		states: ["idle", "patrol", "chase", "attack", "flee"],
		defaultState: "patrol",
		aggroRange: 7,
		fleeThreshold: 0.4,
	},

	drops: [{ type: "salvage", min: 3, max: 8, chance: 0.4 }],

	tags: ["IsUnit", "IsCombat", "IsRanged"],
};
