import type { HeroDef } from "@/entities/types";

export const cplSplash: HeroDef = {
	id: "cpl_splash",
	name: "CPL. SPLASH",
	faction: "ura",
	category: "scout",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"......####......",
					".....#cccc#.....",
					".....#cSSc#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#tttt#.....",
					"....###..###....",
					"................",
				],
			],
			walk: [
				[
					"......####......",
					".....#cccc#.....",
					".....#cSSc#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....##tt##.....",
					"....##...###....",
					"................",
				],
				[
					"......####......",
					".....#cccc#.....",
					".....#cSSc#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#tt##......",
					"....###..##.....",
					"................",
				],
			],
			attack: [
				[
					"......####......",
					".....#cccc#.....",
					".....#cSSc#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S##.",
					"...S#bBBBBb#Scc.",
					"....##BBBB##.##.",
					".....#BBBB#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#tttt#.....",
					"....###..###....",
					"................",
				],
			],
		},
		animationRates: { walk: 8, attack: 10 },
	},

	hp: 80,
	armor: 1,
	damage: 10,
	range: 1,
	attackCooldown: 0.8,
	speed: 18,
	visionRadius: 10,

	cost: {},
	populationCost: 0,
	trainTime: 0,
	trainedAt: "command_post",

	unlockedAt: "mission_8",

	canSwim: true,
	canSubmerge: true,

	portraitId: "cpl_splash",
	unlockMission: "mission_8",
	unlockDescription: "Rescue at Underwater Cache (-10, 15). Unlocks Diver scouts.",

	abilities: [
		{
			id: "deep_dive",
			name: "Deep Dive",
			description: "Become invisible and untargetable for 8 seconds while submerged.",
			cooldown: 25,
		},
		{
			id: "sonar_ping",
			name: "Sonar Ping",
			description: "Reveal all hidden and submerged units within 8 tiles.",
			cooldown: 20,
		},
	],

	tags: ["IsUnit", "IsHero", "IsCombat", "IsScout"],
};
