import type { HeroDef } from "@/entities/types";

export const pvtMuskrat: HeroDef = {
	id: "pvt_muskrat",
	name: "PVT. MUSKRAT",
	faction: "ura",
	category: "siege",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"......####......",
					".....#cccc#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#wwww#.....",
					".....#wwww#.....",
					"..YY.#WWWW#.YY..",
					".YyY.#WWWW#YyY..",
					"..YY###..###YY..",
					"................",
				],
			],
			walk: [
				[
					"......####......",
					".....#cccc#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#wwww#.....",
					".....#wwww#.....",
					"..YY.#WWWW#.YY..",
					".YyY.##WW##YyY..",
					"..YY##...###YY..",
					"................",
				],
				[
					"......####......",
					".....#cccc#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#wwww#.....",
					".....#wwww#.....",
					"..YY.#WWWW#.YY..",
					".YyY.#WW##.YyY..",
					"..YY###..##.YY..",
					"................",
				],
			],
			attack: [
				[
					"......####......",
					".....#cccc#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#wwww#.....",
					".....#wwww#.....",
					".....#WWWW#.....",
					".....#WWWW#..YY.",
					"....###..###YyY.",
					"..............YY",
				],
				[
					"......####......",
					".....#cccc#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#wwww#.....",
					".....#wwww#.....",
					".....#WWWW#.....",
					".....#WWWW#...Y.",
					"....###..###.YyY",
					"..............Y.",
				],
			],
		},
		animationRates: { walk: 6, attack: 8 },
	},

	hp: 120,
	armor: 2,
	damage: 14,
	damageVsBuildings: 40,
	range: 1,
	attackCooldown: 1.5,
	speed: 11,
	visionRadius: 6,

	cost: {},
	populationCost: 0,
	trainTime: 0,
	trainedAt: "command_post",

	unlockedAt: "mission_14",

	portraitId: "pvt_muskrat",
	unlockMission: "mission_14",
	unlockDescription: "Hero mission at Gas Depot (8, 8). Demolition expert.",

	abilities: [
		{
			id: "timed_charge",
			name: "Timed Charge",
			description: "Plant explosive that detonates after 5 seconds for 60 AoE damage.",
			cooldown: 15,
		},
		{
			id: "chain_reaction",
			name: "Chain Reaction",
			description: "Next explosive triggers chain explosions on nearby destructibles.",
			cooldown: 45,
		},
	],

	tags: ["IsUnit", "IsHero", "IsCombat", "IsSiege"],
};
