import type { HeroDef } from "@/entities/types";

export const sgtFang: HeroDef = {
	id: "sgt_fang",
	name: "SGT. FANG",
	faction: "ura",
	category: "siege",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"....######......",
					"...#cccccc#.....",
					"...#TSssST#.....",
					"....######......",
					"...#bbbbbbb#....",
					"..S#bBBBBBBb#S..",
					"..S#bBBBBBBb#S..",
					"..S#bBBBBBBb#S..",
					"..S##BBBBBB##S..",
					"...#BBBBBBB#....",
					"...#CCCCCCCC#...",
					"...#CCCCCCCC#...",
					"...#WWWWWWWW#...",
					"...#WWWWWWWW#...",
					"..####...####...",
					"................",
				],
			],
			walk: [
				[
					"....######......",
					"...#cccccc#.....",
					"...#TSssST#.....",
					"....######......",
					"...#bbbbbbb#....",
					"..S#bBBBBBBb#S..",
					"..S#bBBBBBBb#S..",
					"..S#bBBBBBBb#S..",
					"..S##BBBBBB##S..",
					"...#BBBBBBB#....",
					"...#CCCCCCCC#...",
					"...#CCCCCCCC#...",
					"...#WWWWWWWW#...",
					"...##WWWWWW##...",
					"..##......####..",
					"................",
				],
				[
					"....######......",
					"...#cccccc#.....",
					"...#TSssST#.....",
					"....######......",
					"...#bbbbbbb#....",
					"..S#bBBBBBBb#S..",
					"..S#bBBBBBBb#S..",
					"..S#bBBBBBBb#S..",
					"..S##BBBBBB##S..",
					"...#BBBBBBB#....",
					"...#CCCCCCCC#...",
					"...#CCCCCCCC#...",
					"...#WWWWWWWW#...",
					"...#WWWWWW##....",
					"..####...###....",
					"................",
				],
			],
			attack: [
				[
					"....######......",
					"...#cccccc#.....",
					"...#TSssST#.....",
					"....######......",
					"...#bbbbbbb#....",
					"..S#bBBBBBBb#S..",
					"..S#bBBBBBBb#SYY",
					"..S#bBBBBBBb#SYy",
					"..S##BBBBBB##SYY",
					"...#BBBBBBB#....",
					"...#CCCCCCCC#...",
					"...#CCCCCCCC#...",
					"...#WWWWWWWW#...",
					"...#WWWWWWWW#...",
					"..####...####...",
					"................",
				],
				[
					"....######......",
					"...#cccccc#.....",
					"...#TSssST#..YY.",
					"....######..YyY.",
					"...#bbbbbbb#YY..",
					"..S#bBBBBBBb#S..",
					"..S#bBBBBBBb#S..",
					"..S#bBBBBBBb#S..",
					"..S##BBBBBB##S..",
					"...#BBBBBBB#....",
					"...#CCCCCCCC#...",
					"...#CCCCCCCC#...",
					"...#WWWWWWWW#...",
					"...#WWWWWWWW#...",
					"..####...####...",
					"................",
				],
			],
		},
		animationRates: { walk: 6, attack: 8 },
	},

	hp: 150,
	armor: 4,
	damage: 16,
	damageVsBuildings: 35,
	range: 1,
	attackCooldown: 1.5,
	speed: 12,
	visionRadius: 6,

	cost: {},
	populationCost: 0,
	trainTime: 0,
	trainedAt: "command_post",

	unlockedAt: "mission_12",

	portraitId: "sgt_fang",
	unlockMission: "mission_12",
	unlockDescription: "Rescue at Scale-Guard Stronghold (10, -10). Siege specialist.",

	abilities: [
		{
			id: "breach_charge",
			name: "Breach Charge",
			description: "Plant explosive on building dealing 80 damage after 3 second fuse.",
			cooldown: 20,
		},
		{
			id: "fortify",
			name: "Fortify",
			description: "Nearby allied buildings gain +100 HP for 15 seconds.",
			cooldown: 45,
		},
	],

	tags: ["IsUnit", "IsHero", "IsCombat", "IsSiege"],
};
