import type { HeroDef } from "@/entities/types";

export const sgtBubbles: HeroDef = {
	id: "sgt_bubbles",
	name: "SGT. BUBBLES",
	faction: "ura",
	category: "infantry",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					".....######.....",
					"....#TcccT#.....",
					"....#TssST#.....",
					".....######.....",
					"....#bbbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBbBBb#S.##",
					"...S#bBBBBb#S#c#",
					"...S##BBBB##.#c#",
					"....#BBBBB#..#c#",
					"....#cccccc#.##.",
					"....#CCCCCC#....",
					"....#WWWWWW#....",
					"....#WWWWWW#....",
					"...####..####...",
					"................",
				],
			],
			walk: [
				[
					".....######.....",
					"....#TcccT#.....",
					"....#TssST#.....",
					".....######.....",
					"....#bbbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBbBBb#S.##",
					"...S#bBBBBb#S#c#",
					"...S##BBBB##.#c#",
					"....#BBBBB#..#c#",
					"....#cccccc#.##.",
					"....#CCCCCC#....",
					"....#WWWWWW#....",
					"....##WWWW##....",
					"...##....####...",
					"................",
				],
				[
					".....######.....",
					"....#TcccT#.....",
					"....#TssST#.....",
					".....######.....",
					"....#bbbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBbBBb#S.##",
					"...S#bBBBBb#S#c#",
					"...S##BBBB##.#c#",
					"....#BBBBB#..#c#",
					"....#cccccc#.##.",
					"....#CCCCCC#....",
					"....#WWWWWW#....",
					"....#WWWW##.....",
					"...####..###....",
					"................",
				],
			],
			attack: [
				[
					".....######.....",
					"....#TcccT#.....",
					"....#TssST#.....",
					".....######.....",
					"....#bbbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBbBBb#S###",
					"...S#bBBBBb#Sccc",
					"...S##BBBB##.#c#",
					"....#BBBBB#..##.",
					"....#cccccc#....",
					"....#CCCCCC#....",
					"....#WWWWWW#....",
					"....#WWWWWW#....",
					"...####..####...",
					"................",
				],
				[
					".....######.....",
					"....#TcccT#.....",
					"....#TssST#.....",
					".....######.....",
					"....#bbbbb#..##.",
					"...S#bBBBBb#Sccc",
					"...S#bBbBBb#S###",
					"...S#bBBBBb#S...",
					"...S##BBBB##....",
					"....#BBBBB#.....",
					"....#cccccc#....",
					"....#CCCCCC#....",
					"....#WWWWWW#....",
					"....#WWWWWW#....",
					"...####..####...",
					"................",
				],
			],
		},
		animationRates: { walk: 8, attack: 10 },
	},

	hp: 120,
	armor: 3,
	damage: 15,
	range: 1,
	attackCooldown: 0.8,
	speed: 14,
	visionRadius: 8,

	cost: {},
	populationCost: 0,
	trainTime: 0,
	trainedAt: "command_post",

	unlockedAt: "mission_1",

	portraitId: "sgt_bubbles",
	unlockMission: "mission_1",
	unlockDescription: "Available from the start. Rambo-style warrior-leader.",

	abilities: [
		{
			id: "rallying_cry",
			name: "Rallying Cry",
			description: "Boosts nearby allies attack speed by 25% for 10 seconds.",
			cooldown: 30,
		},
		{
			id: "combat_roll",
			name: "Combat Roll",
			description: "Dodge incoming attack and reposition quickly.",
			cooldown: 8,
		},
	],

	tags: ["IsUnit", "IsHero", "IsCombat"],
};
