import type { UnitDef } from "@/entities/types";

export const diver: UnitDef = {
	id: "diver",
	name: "DIVER",
	faction: "ura",
	category: "scout",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"......####......",
					".....#TTTT#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#tttt#.....",
					"....###..###....",
					"................",
				],
			],
			walk: [
				[
					"......####......",
					".....#TTTT#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....##tt##.....",
					"....##...###....",
					"................",
				],
				[
					"......####......",
					".....#TTTT#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#tt##......",
					"....###..##.....",
					"................",
				],
			],
			attack: [
				[
					"......####......",
					".....#TTTT#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S##.",
					"...S#bBBBBb#Scc.",
					"....##BBBB##.##.",
					".....#BBBB#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#TTTT#.....",
					".....#tttt#.....",
					"....###..###....",
					"................",
				],
			],
		},
		animationRates: { walk: 8, attack: 10 },
	},

	hp: 35,
	armor: 0,
	damage: 8,
	range: 1,
	attackCooldown: 1.0,
	speed: 12,
	visionRadius: 8,

	cost: { fish: 60, salvage: 40 },
	populationCost: 1,
	trainTime: 20,
	trainedAt: "dock",

	unlockedAt: "mission_9",

	canSwim: true,
	canSubmerge: true,

	tags: ["IsUnit", "IsCombat", "IsScout"],
};
