import type { UnitDef } from "@/entities/types";

export const mortarOtter: UnitDef = {
	id: "mortar_otter",
	name: "MORTAR OTTER",
	faction: "ura",
	category: "siege",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"......####......",
					".....#cccc#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					"....C#BBBB#C....",
					"...CC#wwww#CC...",
					"..#CC#wwww#CC#..",
					"..#C.#WWWW#.C#..",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
			],
			walk: [
				[
					"......####......",
					".....#cccc#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					"....C#BBBB#C....",
					"...CC#wwww#CC...",
					"..#CC#wwww#CC#..",
					"..#C.#WWWW#.C#..",
					".....##WW##.....",
					"....##...###....",
					"................",
				],
				[
					"......####......",
					".....#cccc#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					"....C#BBBB#C....",
					"...CC#wwww#CC...",
					"..#CC#wwww#CC#..",
					"..#C.#WWWW#.C#..",
					".....#WW##......",
					"....###..##.....",
					"................",
				],
			],
			attack: [
				[
					"......####......",
					".....#cccc#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#..Y..",
					"...S#bBBBBb#SY..",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					"....C#BBBB#C....",
					"...CC#wwww#CC...",
					"..#CC#wwww#CC#..",
					"..#C.#WWWW#.C#..",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
				[
					"......####..Y...",
					".....#cccc#.Y...",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					"....C#BBBB#C....",
					"...CC#wwww#CC...",
					"..#CC#wwww#CC#..",
					"..#C.#WWWW#.C#..",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
			],
		},
		animationRates: { walk: 6, attack: 8 },
	},

	hp: 45,
	armor: 0,
	damage: 20,
	range: 7,
	attackCooldown: 3.0,
	speed: 5,
	visionRadius: 8,

	cost: { fish: 80, salvage: 60 },
	populationCost: 1,
	trainTime: 35,
	trainedAt: "armory",

	unlockedAt: "mission_9",

	tags: ["IsUnit", "IsCombat", "IsSiege", "IsRanged"],
};
