import type { UnitDef } from "@/entities/types";

export const mudfoot: UnitDef = {
	id: "mudfoot",
	name: "MUDFOOT",
	faction: "ura",
	category: "infantry",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"......####......",
					".....#TssT#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S.##",
					"...S#bBBBBb#S#c#",
					"....##BBBB##.#c#",
					".....#BBBB#..#c#",
					".....#cccc#..##.",
					".....#CCCC#.....",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
			],
			walk: [
				[
					"......####......",
					".....#TssT#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S.##",
					"...S#bBBBBb#S#c#",
					"....##BBBB##.#c#",
					".....#BBBB#..#c#",
					".....#cccc#..##.",
					".....#CCCC#.....",
					".....#WWWW#.....",
					".....##WW##.....",
					"....##...###....",
					"................",
				],
				[
					"......####......",
					".....#TssT#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S.##",
					"...S#bBBBBb#S#c#",
					"....##BBBB##.#c#",
					".....#BBBB#..#c#",
					".....#cccc#..##.",
					".....#CCCC#.....",
					".....#WWWW#.....",
					".....#WW##......",
					"....###..##.....",
					"................",
				],
			],
			attack: [
				[
					"......####......",
					".....#TssT#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S###",
					"...S#bBBBBb#Sccc",
					"....##BBBB##.#c#",
					".....#BBBB#..##.",
					".....#cccc#.....",
					".....#CCCC#.....",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
				[
					"......####......",
					".....#TssT#.....",
					".....#TssT#.....",
					"......####......",
					".....#bbbb#..##.",
					"...S#bBBBBb#Sccc",
					"...S#bBBBBb#S###",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#cccc#.....",
					".....#CCCC#.....",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
			],
		},
		animationRates: { walk: 6, attack: 8 },
	},

	hp: 80,
	armor: 2,
	damage: 12,
	range: 1,
	attackCooldown: 1.2,
	speed: 8,
	visionRadius: 5,

	cost: { fish: 80, salvage: 20 },
	populationCost: 1,
	trainTime: 20,
	trainedAt: "barracks",

	unlockedAt: "mission_1",

	tags: ["IsUnit", "IsCombat"],
};
