import type { UnitDef } from "@/entities/types";

export const riverRat: UnitDef = {
	id: "river_rat",
	name: "RIVER RAT",
	faction: "ura",
	category: "worker",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"......####......",
					".....#SSSS#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"....#bBBBBb#....",
					"....#bBBBBb#..##",
					"....#bBBBBb#.#W#",
					".....#BBBB##.#W#",
					".....#BBBB#..#W#",
					".....#wwww#..##.",
					".....#wwww#.....",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
			],
			walk: [
				[
					"......####......",
					".....#SSSS#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"....#bBBBBb#....",
					"....#bBBBBb#..##",
					"....#bBBBBb#.#W#",
					".....#BBBB##.#W#",
					".....#BBBB#..#W#",
					".....#wwww#..##.",
					".....#wwww#.....",
					".....#WWWW#.....",
					".....##WW##.....",
					"....##...###....",
					"................",
				],
				[
					"......####......",
					".....#SSSS#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"....#bBBBBb#....",
					"....#bBBBBb#..##",
					"....#bBBBBb#.#W#",
					".....#BBBB##.#W#",
					".....#BBBB#..#W#",
					".....#wwww#..##.",
					".....#wwww#.....",
					".....#WWWW#.....",
					".....#WW##......",
					"....###..##.....",
					"................",
				],
			],
			gather: [
				[
					"......####......",
					".....#SSSS#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"....#bBBBBb#....",
					"....#bBBBBb#.##.",
					"....#bBBBBb##W#.",
					".....#BBBB#.#W#.",
					".....#BBBB#..##.",
					".....#wwww#.....",
					".....#wwww#.....",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
				[
					"......####......",
					".....#SSSS#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"....#bBBBBb#.##.",
					"....#bBBBBb##W#.",
					"....#bBBBBb#W#..",
					".....#BBBB##W#..",
					".....#BBBB#.##..",
					".....#wwww#.....",
					".....#wwww#.....",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
			],
		},
		animationRates: { walk: 6, gather: 4 },
	},

	hp: 40,
	armor: 0,
	damage: 5,
	range: 1,
	attackCooldown: 1.5,
	speed: 10,
	visionRadius: 6,

	cost: { fish: 50 },
	populationCost: 1,
	trainTime: 15,
	trainedAt: "command_post",

	unlockedAt: "mission_1",

	gatherCapacity: 10,
	gatherRate: 1,
	buildRate: 1,

	tags: ["IsUnit", "IsWorker"],
};
