import type { UnitDef } from "@/entities/types";

export const sapper: UnitDef = {
	id: "sapper",
	name: "SAPPER",
	faction: "ura",
	category: "siege",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"......####......",
					".....#cccc#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#wwww#.....",
					".....#wwww#.....",
					".....#WWWW#.....",
					"....Y#WWWW#Y...",
					"...YY###..##YY..",
					"................",
				],
			],
			walk: [
				[
					"......####......",
					".....#cccc#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#wwww#.....",
					".....#wwww#.....",
					".....#WWWW#.....",
					"...Y.##WW##.Y..",
					"..YY##...###YY..",
					"................",
				],
				[
					"......####......",
					".....#cccc#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#wwww#.....",
					".....#wwww#.....",
					".....#WWWW#.....",
					"..Y..#WW##..Y..",
					".YY.###..##.YY..",
					"................",
				],
			],
			attack: [
				[
					"......####......",
					".....#cccc#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S...",
					"....##BBBB##....",
					".....#BBBB#.....",
					".....#wwww#.....",
					".....#wwww#.....",
					".....#WWWW#.....",
					".YYY.#WWWW#....",
					"YYyYY###..###...",
					"................",
				],
			],
		},
		animationRates: { walk: 6, attack: 8 },
	},

	hp: 60,
	armor: 1,
	damage: 8,
	damageVsBuildings: 30,
	range: 1,
	attackCooldown: 2.0,
	speed: 7,
	visionRadius: 5,

	cost: { fish: 100, salvage: 50 },
	populationCost: 1,
	trainTime: 30,
	trainedAt: "armory",

	unlockedAt: "mission_5",

	tags: ["IsUnit", "IsCombat", "IsSiege"],
};
