import type { UnitDef } from "@/entities/types";

export const shellcracker: UnitDef = {
	id: "shellcracker",
	name: "SHELLCRACKER",
	faction: "ura",
	category: "ranged",

	sprite: {
		size: 16,
		frames: {
			idle: [
				[
					"......####......",
					".....#TssT#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S..#",
					"...S#bBBBBb#S.#W",
					"....##BBBB##.#W#",
					".....#BBBB#..#W.",
					".....#wwww#..#W.",
					".....#wwww#..#..",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
			],
			walk: [
				[
					"......####......",
					".....#TssT#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S..#",
					"...S#bBBBBb#S.#W",
					"....##BBBB##.#W#",
					".....#BBBB#..#W.",
					".....#wwww#..#W.",
					".....#wwww#..#..",
					".....#WWWW#.....",
					".....##WW##.....",
					"....##...###....",
					"................",
				],
				[
					"......####......",
					".....#TssT#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S..#",
					"...S#bBBBBb#S.#W",
					"....##BBBB##.#W#",
					".....#BBBB#..#W.",
					".....#wwww#..#W.",
					".....#wwww#..#..",
					".....#WWWW#.....",
					".....#WW##......",
					"....###..##.....",
					"................",
				],
			],
			attack: [
				[
					"......####......",
					".....#TssT#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#.....",
					"...S#bBBBBb#S...",
					"...S#bBBBBb#S..#",
					"...S#bBBBBb#S.#W",
					"....##BBBB##.#WW",
					".....#BBBB#..#W.",
					".....#wwww#..#..",
					".....#wwww#.....",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
				[
					"......####......",
					".....#TssT#.....",
					".....#SssS#.....",
					"......####......",
					".....#bbbb#..#..",
					"...S#bBBBBb#S#W.",
					"...S#bBBBBb#S#WW",
					"...S#bBBBBb#S.#W",
					"....##BBBB##..#.",
					".....#BBBB#.....",
					".....#wwww#.....",
					".....#wwww#.....",
					".....#WWWW#.....",
					".....#WWWW#.....",
					"....###..###....",
					"................",
				],
			],
		},
		animationRates: { walk: 6, attack: 10 },
	},

	hp: 50,
	armor: 0,
	damage: 10,
	range: 5,
	attackCooldown: 1.5,
	speed: 9,
	visionRadius: 7,

	cost: { fish: 70, salvage: 30 },
	populationCost: 1,
	trainTime: 22,
	trainedAt: "barracks",

	unlockedAt: "mission_3",

	tags: ["IsUnit", "IsCombat", "IsRanged"],
};
